language: php
php:
  - 7.2
before_script:
  - composer install
  - cp tests/fixtures.dist.ini tests/fixtures.ini
  - cp tests/datacash_magic_numbers.dist.php tests/datacash_magic_numbers.php
script:
    - ./bin/phpunit tests/
after_success:
  - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
notifications:
  email: false
